# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            Cade Ward
tagline:          'A Jekyll theme'
description:      'Full Stack Web Developer'
url:              http://cadeward.com
baseurl:          /

author:
  name:           'Cade Ward'
  url:            https://twitter.com/cadebward

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/cadew/

resume:  		  https://resume.cadeward.com/
